server:
  port: 11000
logging.level.root: error
logging.level.org.ileler: debug
#logging.level.org.springframework.cloud.sleuth: debug
spring:
  zipkin:
    base-url: http://localhost:10003
  sleuth:
    sampler:
      percentage: 1.0
zuul:
#  ignoredServices: '*'
#  ribbon:
#    eager-load:
#      enabled: true
  routes:
    s1:
      path: /s1/**
      serviceId: org.ileler.service1
      stripPrefix: true
    s2:
      path: /s2/**
      serviceId: org.ileler.service2
      stripPrefix: true